# Generated by Django 5.1.1 on 2026-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('accountant', 'Бухгалтер'), ('logistician', 'Логист'), ('crew', 'Экипаж судна'), ('captain', 'Капитан'), ('fleet_manager', 'Управляющий флотом'), ('dispatcher', 'Диспетчер'), ('engineer', 'Инженер')], default='crew', max_length=20),
        ),
    ]
