# Generated by Django 5.1.1 on 2026-02-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('counterparty_type', models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик'), ('both', 'Клиент и поставщик')], max_length=20, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Название банка')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('contract_type', models.CharField(choices=[('sale', 'Договор продажи'), ('purchase', 'Договор поставки'), ('service', 'Договор услуг'), ('other', 'Прочее')], max_length=20, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('expired', 'Истек'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='finance_app.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
                'unique_together': {('number', 'counterparty')},
            },
        ),
    ]
