# Generated by Django 5.1.1 on 2026-02-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('employee_type', models.CharField(choices=[('shore', 'Береговой персонал'), ('crew', 'Экипаж судна')], max_length=20, verbose_name='Тип')),
                ('ship_name', models.CharField(blank=True, help_text='Для экипажа', max_length=100, verbose_name='Название судна')),
                ('external_ship_id', models.CharField(blank=True, max_length=100, verbose_name='ID судна из блока Флот')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Счет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance_app.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья расходов',
                'verbose_name_plural': 'Статьи расходов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('date', models.DateField(verbose_name='Дата счета')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('invoice_type', models.CharField(choices=[('outgoing', 'Исходящий (клиенту)'), ('incoming', 'Входящий (от поставщика)')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Файл счета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_app.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_app.counterparty', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер платежа')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('payment_type', models.CharField(choices=[('incoming', 'Поступление (от клиента)'), ('outgoing', 'Расход (поставщику)')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('card', 'Банковская карта'), ('offset', 'Взаимозачет')], max_length=20, verbose_name='Способ оплаты')),
                ('external_order_id', models.CharField(blank=True, help_text='Для интеграции с блоком Сбыт', max_length=100, verbose_name='ID заказа из CRM')),
                ('external_supply_request_id', models.CharField(blank=True, help_text='Для интеграции с блоком Флот', max_length=100, verbose_name='ID заявки на снабжение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance_app.counterparty', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance_app.invoice', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('days_worked', models.IntegerField(default=0, verbose_name='Отработано дней')),
                ('hours_worked', models.IntegerField(default=0, verbose_name='Отработано часов')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад/ставка')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого начислено')),
                ('voyage_days', models.IntegerField(default=0, help_text='Для экипажа', verbose_name='Дней в рейсе')),
                ('voyage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка за день в рейсе')),
                ('voyage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рейсовые')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждено'), ('paid', 'Выплачено')], default='draft', max_length=20, verbose_name='Статус')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто начислил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='finance_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Начисление зарплаты',
                'verbose_name_plural': 'Начисления зарплаты',
                'ordering': ['-period_end'],
            },
        ),
    ]
