# Generated by Django 5.1.1 on 2026-03-18 10:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название судна')),
                ('type', models.CharField(choices=[('fishing', 'Промысловое'), ('transport', 'Транспортное'), ('passenger', 'Пассажирское')], default='fishing', max_length=20, verbose_name='Тип судна')),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='Номер ИМО')),
                ('status', models.CharField(choices=[('at_sea', 'В море'), ('in_port', 'В порту'), ('under_repair', 'На ремонте'), ('out_of_service', 'Выведено из эксплуатации')], default='in_port', max_length=20, verbose_name='Статус')),
                ('current_location', models.CharField(blank=True, max_length=300, verbose_name='Текущее местоположение')),
                ('technical_condition', models.TextField(blank=True, verbose_name='Техническое состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Судно',
                'verbose_name_plural': 'Судна',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Плановое'), ('emergency', 'Аварийное'), ('upgrade', 'Модернизация'), ('inspection', 'Осмотр')], default='scheduled', max_length=20, verbose_name='Тип ТО/ремонта')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость (руб.)')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Подрядчик')),
                ('documents', models.FileField(blank=True, null=True, upload_to='maintenance_docs/', verbose_name='Документы')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.ship', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание/Ремонт',
                'verbose_name_plural': 'Технические обслуживания/Ремонты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('captain', 'Капитан'), ('first_mate', 'Старший помощник'), ('engineer', 'Механик'), ('seaman', 'Матрос'), ('cook', 'Кок'), ('other', 'Другое')], default='seaman', max_length=20, verbose_name='Должность/Звание')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания контракта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('assigned_ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_members', to='fleet.ship', verbose_name='Закрепленное судно')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Члены экипажа',
                'ordering': ['rank', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выхода')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возвращения')),
                ('fishing_area', models.CharField(choices=[('okhotsk', 'Охотское море'), ('bering', 'Берингово море'), ('japan', 'Японское море'), ('pacific', 'Тихий океан'), ('atlantic', 'Атлантический океан'), ('other', 'Другое')], default='okhotsk', max_length=30, verbose_name='Район промысла')),
                ('catch_plan', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='План добычи (тонны)')),
                ('actual_catch', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактическая добыча (тонны)')),
                ('description', models.TextField(blank=True, verbose_name='Описание рейса')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='fleet.ship', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-start_date'],
            },
        ),
    ]
