# Generated by Django 5.1.1 on 2026-03-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='voyages', to='fleet.crewmember', verbose_name='Экипаж'),
        ),
    ]
