# Generated by Django 5.1.1 on 2026-03-19 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_voyage_crew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-start_date'], 'verbose_name': 'Техническое обслуживание/Ремонт', 'verbose_name_plural': 'Технические обслуживания/Ремонты'},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='date',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('planned', 'Плановое'), ('emergency', 'Аварийное'), ('current', 'Текущий ремонт')], default='planned', max_length=20, verbose_name='Тип ремонта'),
        ),
    ]
