# Generated by Django 5.1.1 on 2026-03-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_maintenance_repair_team_delete_repairteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='contractor_text',
            field=models.CharField(blank=True, help_text='Если контрагент не выбран, можно указать вручную', max_length=200, verbose_name='Подрядчик (текст)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='fleet.contractor', verbose_name='Подрядчик'),
        ),
    ]
