# Generated by Django 5.1.1 on 2026-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_contractor_maintenance_contractor_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ship', 'Судно'), ('voyage', 'Рейс'), ('maintenance', 'Ремонт'), ('crew', 'Экипаж')], max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID сущности')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocking', 'Blocking')], max_length=20, verbose_name='Severity')),
                ('code', models.CharField(max_length=100, verbose_name='Код проблемы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['is_resolved', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'code'), name='fleet_notification_unique_problem')],
            },
        ),
    ]
