# Generated by Django 5.1.1 on 2026-04-12 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipCrewRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(choices=[('fishing', 'Промысловое'), ('transport', 'Транспортное'), ('passenger', 'Пассажирское')], max_length=20, verbose_name='Тип судна')),
                ('role', models.CharField(choices=[('captain', 'Капитан'), ('first_mate', 'Старший помощник'), ('engineer', 'Механик'), ('seaman', 'Матрос'), ('cook', 'Кок'), ('other', 'Другое')], max_length=20, verbose_name='Роль экипажа')),
                ('required_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Требуемое количество')),
            ],
            options={
                'verbose_name': 'Требование к составу экипажа',
                'verbose_name_plural': 'Требования к составу экипажа',
                'ordering': ['ship_type', 'role'],
                'constraints': [models.UniqueConstraint(fields=('ship_type', 'role'), name='fleet_ship_crew_requirement_unique_role_per_type')],
            },
        ),
    ]
